services:
  app:
    image: ebiznes01
    build: .
    container_name: ebiznes01
    environment:
      - SDKMAN_DIR=/root/.sdkman
      - PATH=/root/.sdkman/bin:/root/.sdkman/candidates/gradle/current/bin:${PATH}
      - GRADLE_HOME=/root/.sdkman/candidates/gradle/current
    command: bash -c "source /root/.sdkman/bin/sdkman-init.sh && gradle run"
